/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_km1930_dynamicbicycleclient_serialndk_Serial */

#ifndef _Included_com_km1930_dynamicbicycleclient_serialndk_Serial
#define _Included_com_km1930_dynamicbicycleclient_serialndk_Serial
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_km1930_dynamicbicycleclient_serialndk_Serial
 * Method:    OpenSerial
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_km1930_dynamicbicycleclient_serialndk_Serial_OpenSerial
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_km1930_dynamicbicycleclient_serialndk_Serial
 * Method:    SetSerialBaud
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_km1930_dynamicbicycleclient_serialndk_Serial_SetSerialBaud
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_km1930_dynamicbicycleclient_serialndk_Serial
 * Method:    ReadSerialBuf
 * Signature: ([SI)I
 */
JNIEXPORT jint JNICALL Java_com_km1930_dynamicbicycleclient_serialndk_Serial_ReadSerialBuf
  (JNIEnv *, jclass, jshortArray, jint);

/*
 * Class:     com_km1930_dynamicbicycleclient_serialndk_Serial
 * Method:    WriteSerialBuf
 * Signature: ([SI)I
 */
JNIEXPORT jint JNICALL Java_com_km1930_dynamicbicycleclient_serialndk_Serial_WriteSerialBuf
  (JNIEnv *, jclass, jshortArray, jint);

/*
 * Class:     com_km1930_dynamicbicycleclient_serialndk_Serial
 * Method:    CloseSerial
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_km1930_dynamicbicycleclient_serialndk_Serial_CloseSerial
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
